### PR TITLE
OpenCore 0.8.6 update and ready for MacOs 13.0.1

### PR DESCRIPTION
**Pull request by iuri1911**

### CODE REVIEW

**Comment by iuri1911** [comment]
consegui o Hackintosh perfeito com essas configs.

**Review by edulemasson — APPROVED** [review]
It sounds good

**Review by edulemasson — APPROVED** [review]
Awesome this new release for this base EFI. You did the job!

**Comment by luchina-gabriel** [comment]
Thanks Team, PR approved 🤘🏼

**Pull request merged**
